global:
  scrape_interval: 15s
  scrape_timeout: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'swapstats-app'
    static_configs:
      - targets: ['app:9091']
        labels:
          instance: 'app-1'
