# config_dev.yaml — swap-stats (prod-like, но экономно по ресурсам)

app:
  instance_id: "agg-1"        # ID инстанса
  grace: "120s"               # допускаем опоздание событий
  snapshot_interval: "5s"     # период снапшотов состояния
  shutdown_timeout: "10s"

logging:
  level: "info"               # debug|info|warn|error
  format: "json"              # json|console

security:
  jwt:
    enabled: true # включить проверку токенов на HTTP/WS
    alg: "RS256"
    public_key_path:  "/infra/secrets/jwtRS256.key.pub"
    private_key_path: "/infra/secrets/jwtRS256.key"
    audience: "swap-stats" # кого адресует токен
    issuer:   "swap-stats-auth" # кто этот токен выпустил

rate_limit:
  by_jwt: # лимитируем по sub (клиент/пользователь)
    refill_per_sec: 50 # ?
    burst: 200 # ?
  by_ip:
    refill_per_sec: 20 # ?
    burst: 60 # ?

ingest:
  broker_type: "redpanda"     # redpanda|kafka
  brokers: ["redpanda:9092"]
  topic: "raw-swaps"          # пока что 1 партиция, в prod увеличить
  group_id: "swap-stats"      # имя consumer группы (влияет на оффсеты)
  start: "latest"             # перечитываем ли мы сообщения(earliest|latest)
  max_bytes: 1048576          # ограничение на размер сообщения 1 MiB
  max_inflight: 64            # сдерживаем параллелизм обработки, чтобы не упираться в RAM/CPU
  session_timeout: "30s"      # ?
  rebalance_timeout: "60s"    # ?

dedupe:
  ttl: "24h"                  # время жизни ключа(event_id) при dedupe(дубликаты)

stores:
  redis: # неймспейс для ключей (swapstats:*)
    addr: "redis:6379"
    username: "default"
    password: 5JKksp3HVfAe
    db: 2
    prefix: "swapstats:"
    # жёсткие лимиты, чтобы не залипать на сети
    dial_timeout: "1s"
    read_timeout: "2s"
    write_timeout: "2s"

  clickhouse:
    dsn: "tcp://clickhouse:9000?database=swaps&compress=true&dial_timeout=2s&read_timeout=10s&write_timeout=10s"
    writer:
      batch_max_rows: 1000 # копим до 1000 строк в батче или сбрасываем каждые batch_max_interval
      batch_max_interval: "200ms"
      max_retries: 5
      retry_backoff: "200ms"

pubsub:
  nats:
    url: "nats://nats:4222"
    broadcast_prefix: "ws.broadcast.token." # префикс для сабжектов fan-out между инстансами (* ws.broadcast.token.USDC)

api:
  http:
    addr: ":8080"
    read_timeout:  "10s"
    write_timeout: "10s"
    idle_timeout:  "60s"
    cors:
      enabled: true
      origins: ["*"]          # в проде — сузим и зафиксировать домен
      methods: ["GET","POST","OPTIONS"]
      headers: ["Authorization","Content-Type"]

  ws:
    coalesce_ms: 100           # коалесинг обновлений (сливаем события и шлём пачкой 10 раз в секунду)
    max_conn: 5000             # лимит одновременных клиентов
    read_limit_bytes: 1048576  # 1 MiB лимит входящих сообщений
    write_timeout: "5s"        # не даем записи висеть
    heartbeat_interval: "30s"  # чтобы закрывать мертвые сокеты

metrics:
  prometheus: ":9091" # /metrics
  pprof: ":6060"
